label TapaniKaarina_grave:
    "... Finally. We're back here."
    "... What a day."
    "It was fascinating to hear what happened to all the others — that there even were others. To meet them."
    "But I've always wondered, naturally."
    "Why weren't they there to raise me?"
    "Auntie never told me the specifics, just that there was an accident."
    "... If dad hadn't died..."
    "I'd have known about all these people."
    v "So... You truly want to find out what happened to them?"
    r "Of course I do! That's why I agreed to help."
    "His eyes get a strange glint in them. It's like he tenses, just a bit."
    v "Very well then. I'll uphold my end of the bargain."
    v "As long as you're ready for what you're about to hear."
    "Despite the sensation of creeping doom hanging in the air, I nod."
    "He reaches out his hand toward the stone."

    v "Tapani Ilvessalo, born 7th of March 1965, and Kaarina Ilvessalo, neé Heikkilä, born 2nd  of June 1970."
    v "Tapani, raised by his father and uncle, grew up fascinated by the skies above."
    v "His studies in meteorology led him to meet Kaarina, a fellow aspiring meteorologist."
    v "They married, and soon after had their first child. Rene."
    v "They kept the baby's name a secret from their respective families — those that they had left. A fun surprise for the christening."
    v "Their lives were happy and ordinary."
    v "One day, on a freezing cold January evening, came a knock at the door."
    v "A strange man stood behind it — old fashioned, four horns atop his head and scales on his cheeks — who proclaimed himself to be Tapani's great grandfather."
    v "He'd been searching for his family for such a long time. Now that he'd finally found someone with his eyes, he just wanted to talk! Catch up a bit."
    v "Tapani, like a fine young gentleman, invited him in for coffee. His hands shook as he poured him a cup."
    v "His great-grandfather, looking but a few years older than him, asked if he knew where the rest of his family had gone. If he's met anyone else with their eyes and tiny horns."
    v "Tapany says: \"I reckon they're all dead. Only knew my dad's side, so don't know much about the rest of the lot.\""
    v "Oh, really now? Well, that's a shame."
    v "What about you? Any children yet?"
    t "Haha, no, not yet. Just me and the wife for now."
    "He lied. An archdemon wouldn't come knocking on their door without a purpose."
    v "Well, that's a relief."
    v "You see, I have this... ailment. An affliction."
    v "Something that cannot be cured, that can't be removed."
    v "And I'll be frank with you — no need to waste both our precious times..."
    v "I'd rather get rid of it."
    v "I have to vacate this body. And yours seems to be in fine shape."
    t "... What? No, wait —"
    t "Is— How would you even do that?!"
    v "I have my ways. Would you like to experience them?"
    v "It'll be painless, I promise! You see, I won't even have to touch you."
    t "P-please, sit back down!"
    v "Just a little flick of the wrist, and I'll open my eyes again, from inside your skull this time. I'll handle the pain, don't worry."
    v "Mind if I borrow one of your knives?"
    t "W-what? No, stop that—!"
    t "Don't!"

    "Tapani and his beloved wife met their swift ends at the claws of a blinded beast, in the burning husk of a newborn home."
    "But there was a sound amidst the creeping heat."
    "The cries of a young baby, echoing from upstairs."
    "A child. Only a few months old. Familiar blood."
    "It would have accommodated him. And it was so small, it didn't even understand its own existence yet."
    "It wouldn't know what it had lost."
    "But the man stumbled out, the baby bundled up in his scarf."
    "A young woman appeared, panicking. Searching for her sister."
    a "Oh my God ... Kaarina?! Kaarina!"
    v "I'm afraid it's too late for them."
    a "Are— Who are you?! Have you called 112?!"
    "The man said nothing. And handed the baby to her."
    a "He's... They didn't—!"
    a "... They didn't even get to name him... God — I don't know his name...!"
    v "... His name would have been Rene."
    "And so the man disappeared into the night, clutching at his eyes that never did quite heal."
    "To lie back down to sleep, to wait until the right time."
    "To search for his living blood once more."

    if p_emp <= 10 and p_rep <= 10 and p_emp >= 5 and p_rep >= 5:
        "...What?"
        r "..."
        r "It was you."
        r "It was your fault."
        v "Yes."
        "It's like all my limbs are  stukc in ice."
        "It's hard to think."
        "He's... He has to be lying, but — Why would he?"
        "...No."
        "He isn't. He's telling the truth."
        r "You killed my parents."
        v "Well, yes. Thought not unprovoked, mind you, I have at least some manners."
        v "And I did save your life then, so—"
        r "Some ma—! What the hell do you mean \"some manners\"?!"
        r "What were you trying to do?! Why did—"
        v "Look. I understand why you feel this way."
        if p_emp >= p_rep:
            v "I know you're a bright, kind man."
        else:
            v "I like you. You've got a spark that I enjoy."
        v "But it simply is not enough."
        v "Your existence could be more useful in service of something much greater."
        r "What the {i}hell{/i} does that mean?!"
        v "I told you the truth. I was looking for my relatives, and I was fairly certain only you were left alive. But I needed to make sure."
        v "The process can be... unreliable if there are more options."
        v "I am afflicted. I need to get rid of this body."
        v "I quite enjoy my current form. I'd hate to spend the rest of my days crawling on the ground like a common worm."
        v "Your father wasn't willing to give back the life I had bestowed him, so..."
        "My legs won't stop shaking. It's hard to think."
        v "If you'd be so kind as to cooperate."
        v "I'll put your years to good use. Mine are effectively endless, after all."
        menu:
            "Neutral ending.":
                jump Neutral_ending

            "Bad ending.":
                jump Bad_ending
    elif p_rep <=5 and p_emp <= 5:
        "...What?"
        r "..."
        r "It was you."
        r "It was your fault."
        v "Yes."
        "It's like all my limbs are  stukc in ice."
        "It's hard to think."
        "He's... He has to be lying, but — Why would he?"
        "...No."
        "He isn't. He's telling the truth."
        r "You killed my parents."
        v "Well, yes. Thought not unprovoked, mind you, I have at least some manners."
        v "And I did save your life then, so—"
        r "Some ma—! What the hell do you mean \"some manners\"?!"
        r "What were you trying to do?! Why did—"        
        v "God, could you possibly make any more noise?"
        v "You're frightening the birds."
        r "But—!"
        "He holds up a single finger and I feel my throat closing."
        "I'm —"
        "I'm drowning."
        "My hands feel cold."
        "Help."
        v "Now..."
        v "If you'd be so kind as to stop struggling,"
        v "and give me the life I'm owed."
        v "... Not like any of yours is going to waste."
        v "I suppose there's a silver lining. You know for a fact there's no one left to grieve you."
        menu:
            "Neutral ending.":
                jump Neutral_ending

            "Bad ending.":
                jump Bad_ending

    else: #Mietitään myöhemmin lisää miten tää mekaanisesti toimii mut good ending on ny tässä. Perkele.
        "... What?"
        r "..."
        r "So it was your fault."
        v "...Yes."
        "It's like all my limbs are stuck in ice. It's hard to think."
        "He's… He has to be lying, but — Why would he?"
        "... No. He isn't."
        "He's telling the truth."
        r "You killed my parents."
        v "...Well, yes. I know it won't fix anything, but I didn't intend to. I lost control."
        v "And I did save your life then, so—"
        r "Lost contr—! What the hell do you mean 'lost control', what excuse is that?!"
        r "What were you trying to do!? Why did—"
        r "..."
        r "... Whatever it was, that's why you're here now. To try and do it again. With me, this time."
        v "I wasn't lying."
        r "I know that—"
        v "I am afflicted. I'm…"
        v "..."
        r "..."
        r "Why is this taking so long?"
        v "...?"
        r "Well, come on then! Do it!"
        v "I—"
        r "Do it! That's why you're here! That's why {i}I'm{/i} here!"
        r "Just— Put me out of my misery!"
        "I don't know why I'm saying that."
        "I don't mean it… I think."
        "I think…"
        v "... I should, shouldn't I?"
        v "..."
        v "Say…"
        v "Could you help me find one last grave?"
        r "Huh? I thought there—"
        v "There's one more. I presume there is."
        v "The mother of Aarne and Lennart."
        v "Before anything else, I'd like to know what happened to her."
        v "... If you'd be so kind."
        r "..."
        "I don't owe him anything."
        "I don't think I can really trust him… even if he's not a liar."
        "... But I don't know what else to do."
        "It all feels… empty and pointless."
        "There's nothing to go back to, anyway. An empty house, an empty room, an empty life."
        "I have nothing better to do."


label graveyard_5: #Tää voi myöhemmin olla oma p-a-c sektio mut nyt railroadataa
    scene section1
    jump Anni_grave

label Anni_grave:
    r "..."
    r "Well. There she is."
    v "What was her name?"
    r "Anni. Heikkilä. Her husband Jussi is also here."
    v "... Would you like me to...?"
    r "No, it's... I know her story already."
    v "You don't want to hear an outside perspective?"
    r "I'd rather not. It's probably not any different than the one I know."
    v "Well... Mind telling an old man about {i}your{/i} perspective?"
    r "... Anni. Auntie."
    r "I've always lived with her, that's just how it was."
    r "She never pretended that she was my mom, you know. But to me, she was."
    r "Helped me with homework, bandaged up my knees whenever I fell off the bike."
    r "Drove me to the health centre after I fell skating, read me all my favourite bedtime stories whenever I asked."
    r "Sometimes she read her old comics to me and..."
    r "But then I... One summer, I did something."
    v "...?"
    r "I don't think she ever forgave me."
    "I can't stop talking. Why can't I stop talking?"
    "Is it — No it's not. I can stop. I could. {i}But I don't want to."
    r "After that, I didn't really speak with her anymore."
    r "It was like walking on eggshells."
    v "Did she become... unpleasant?"
    r "No. No, she didn't never did. It was worse that she didn't."
    r "And it hurt a lot more. Knowing she didn't mean it anymore."
    r "I knew it. That she hated me for what I'd done."
    r "But even after her and Jussi split up, she let me stay. Bought my laptop and all my upper secondary school books."
    r "I stayed in my room so much, I..."
    r "I didn't initially notice."
    r "She couldn't leave the hospital anymore."
    r "Cancer."
    "..."
    r "I was afraid to go visit her. And then she passed away."
    r "... She probably thought I hated her."
    v "..."
    v "Poor woman."
    r "..."
    v "And you've been on your lonseome ever since?"
    r "Yeah. It's been a few years."
    r "It's been fine."
    v "Has it, now?"

    menu:
        "Not like it's going to get any better.":
            $ p_emp -= 2
            $ p_rep -= 2
            r "... I think this is how it's going to be from now on."
            r "I've gotten used to it."
            r "It'll be fine."
            r "I'm not getting into a university with my grades, or get a job..."
            r "But it'll be fine. Like it always has."
            v "I'm sure you mean that."
            v "... A hopeless case, aren't you?"

        "It hasn't. But it'll get better.":
            $ p_emp += 2
            $ p_rep += 2
            r "... No. It's been like that for so long that it's hard to imagine it any different, you know?"
            r "But... I guess things can change. Maybe if I manage to get a job, or get into univeristy—"
            v "Neither will automatically change anything for the better."
            r "It'd be something, at least."
            v "You've bloomed into quite the optimist, haven't you?"
            r "Not really? I'm just being realistic. Change helps."
            r "Like... Maybe today hasn't been that terrible. It's been pretty interseting, hearing you talk about the past and so on."
            v "Well now! Don't be so open handed with the praise. You don't want people to get used to it."
            r "Just stating facts, that's all."
    v "..."
    v "Your aunt... she was married, right?"
    v "Didn't she have any children of her own?"

    if p_rep >= 6:
        r "..."
        v "... Rene?"
        r "She did."
        r "..."
        "I don't know why he's so interested. He's not related to him at all."
        "But... I get the feeling he won't let me drop the matter now that I've said it."
        r "... Want to meet him?"
        v "Lead the way. If you please."
        jump Elias_grave
    else:
        menu:
            "No.":
                v "... If you insist."
            "No.":
                v "... If you insist."
            "No.":
                v "... If you insist."
        "..."
        r "... So what happened to mom and dad?"
        r "You promised."
        v "Oh, yes. I almost forgot."
        v "Well, get to it. The sun will set before you hear what happened if you just stand there like a doornail."
        jump TapaniKaarina_grave


label Elias_grave:
    r "..."
    v "..."
    v "... So. This is your cousin, I take it?"
    r "Elias."
    r "We... He was more like a brother, though. I knew he wasn't."
    "Why did I come here?"
    r "A bit older than me, so he was always there to kick the shit out of anyone who dared to bully me."
    r "Got into a lot of trouble because of that."
    "It's all flooding back..."
    "And I can't stop."
    "..."
    r "He was a prankster. Put fake spiders in my bed and made me eat rabbit droppings when we were kids."
    r "Then, this one midsummer..."
    #CGs begin
    r "We were at grandparents' cottage."
    r "Me and Elias went swimming. Alone."
    r "I got tired, and sat on the edge of the pier. Dangling my feet in the water. Pretending they were big oars."
    r "I don't know what he thought he was doing, or why..."
    r "But he dove underwater."
    r "It was murky, I couldn't see where he went."
    r "And then I got scared when he didn't come back up."
    r "I thought something had taken him. He just wasn't coming back up."
    r "Something grabbed my ankle."
    r "I didn't— I didn't realise—"
    r "I just kicked on instinct."
    r "... And then I just sat there. Waiting for him to come back up."
    r "I thought he was just pulling a prank on me again."
    r "I sat there, waiting, waiting, and waiting, until I knew he wasn't coming back up. But I had no idea what to do."
    r "..."
    r "...They found his body three days later."
    v "..."
    v "My condolences."
    r "It's alright."
    v "..."
    v "How old were you?"
    r "Ten."
    v "..."
    v "I take it that you think your aunt blamed you for his death?"
    r "I don't 'think' anything, I know it."
    r "Who wouldn't, right?"
    r "My grandparents did, at least."
    v "But it didn't sound like your aunt held any grudged."
    r "She would have kicked me out if she had the heart to. Probably thought she owed it to mom to take care of me."
    v "... Alright then. Maybe she did blame you."
    v "She blamed you for the death of one of her sons, but couldn't bear the idea of losing both."
    r "Stop."
    v "Even if she'd thought that it wasn't an accident,"
    v "She loved you too much to let you suffer because of her."
    r "..."
    r "That's not true. You don't know that."
    v "Are you sure?"

    menu:
        "She didn't love me.":
            $ p_rep -= 5
            r "I know she hated my guts after that."
            r "I know she — that if it had been a choice,"
            r "She would have chosen Elias over me."
            r "I should have drowned in that lake."
            r "And things would have been so much easier. Better."
            r "... Maybe her and Jussi would have stayed together, maybe my grandparents would have still talked to her..."
            r "... I shouldn't be here at all."
            v "..."
            v "{size=-12}If I had known you'd wished for death so badly, I wouldn't have..."
            r "What did you{nw}"
            v "Nothing."
            r "..."
            v "We should go."
            v "... What? Don't just stand there, come along now."
            jump TapaniKaarina_grave

        "... She loved me.":
            $ p_rep += 5
            r "... Yeah."
            r "Yeah, maybe... Maybe she didn't. Hate my guts, I mean."
            r "I dunno, \"love\"'s a strong word."
            v "So is hate."
            r "Guess so."
            r "..."
            r "I wonder why she never asked me to come to the hospital."
            v "Perhaps she thought you'd be better off not seeing her like that."
            v "It can be brutal to see a loved one wither away like that."
            r "... You're not speaking from experience, are you?"
            v "Of course not."
            v "But I, for one, don't doubt that she loved you with all her heart. And if I may be so bold as to guess,"
            v "she'd like you to live a life you're proud of."
            r "..."
            r "We should go."
            v "..."
            r "... What?"
            v "It's nothing."
            v "..."
            r "What are you standing there for? Let's go."
            r "To mom and dad then, right?"
            v "Yes... Yes, I suppose it is that time."
            jump TapaniKaarina_grave

label Neutral_ending:
    "I can't do much else other than watch. My body just refuses to listen."
    "He hesitates for a moment."
    "But his body is lifeless on the ground before I can try and stop him."
    "..."
    "..."
    "Why did he…?"
    "What's happening?"
    "What's happening to me?"
    "Something is. I feel different."
    "I can feel myself changing. I'm slipping away."
    "My hands feel different."
    "I'm sliding down an icy slope and I can't stop myself. There's no end."
    "Endless."
    "Endlessly sliding, slipping, slithering."
    "It's awful. Cruel."
    "Why did he do this to me?"
    "I'm… I'm…"
    "I'm not me…"
    "..."
    "..."
    v "Well, then. What a wholly unpleasant experience."
    v "... Marchosias, you lying hag."
    #Cool ending CG where Valac is walking away in Rene's clothes with his own coat draped over his arm
    return


label Bad_ending:
    "I take off running before I realise what's truly happening."
    "There's gurgling laughter behind me. I hear it even after reaching the graveyard gates."
    v "Silly boy."
    v "This isn't something you can outrun. You can try."
    v "But it won't help you."
    v "I can smell your blood."
    #CGS Rene juoksee kotiin
    #Door closes
    "My legs give out."
    "Throat hurts. Head hurts."
    "What will— I won't be…"
    "... 'From inside your skull'..."
    "So, I won't… exist, after he…"
    "..."
    "... I remember."
    "Auntie kept Elias' sheath knife. He got it as his 10th birthday present."
    "For opening sausage packets that we'd grill on the bonfire."
    "For opening bottles."
    "For whittling."
    "That tiny wooden spoon you gave me."
    "..."
    "I guess you got your revenge this way."
    "... I should have done this a long time ago."
    "I'm so sorry, Elias."
    return









